name: Deploy Python Application

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]
  #  paths:
  #    - '**.py'
  #    - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_APP_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-bcl-reviewer'
          package: .
          
      - name: Show Deployment URL
        run: |
          echo "Die App wurde deployed und ist verfügbar unter: https://app-bcl-reviewer.azurewebsites.net" 